### PR TITLE
Mel tag 14

### PR DESCRIPTION
**Pull request by MelQuan95**
# Description
Ticket Number 14, Create tag. I added a AddTag function to the TagRepository with SQL, added a view for create so the user can create/Add a new tag in the list of all tags. Also added the get and post in the TagController with try and catch . 

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# Testing Instructions

-in your terminal 

1. git add and git commit on your branch.
2. git checkout main
3. git fetch -a
4. git checkout mel-Tag-14
5. Navigate to the directory **/tabloidmvc-the-brogrammers**
6. start TabloidMVC.sln
7. Make sure your db is created with seed data if not done yet.  RUN -   **https://github.com/NewForce-Cohort-5/tabloidmvc-the-brogrammers/blob/017ce8dd8478582f0227d20e2079ed705c60f45e/SQL/01_TabloidMVC_Create_DB.sql & https://github.com/NewForce-Cohort-5/tabloidmvc-the-brogrammers/blob/017ce8dd8478582f0227d20e2079ed705c60f45e/SQL/02_TabloidMVC_Seed_Data.sql)** 

8. start the server
9. login as as Admin **admin@example.com ** 
10. Go to Tag Management on the NavBar 
11. Click Create New Tag
12. Create new Tag with the all fields
13. save and you should see the new tag on the tag list

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors
- [ ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by sarahebrooks12** [comment]
Need SQL data for mel email

**Comment by sarahebrooks12** [comment]
👼

**Review by ded-possum — APPROVED** [review]
Everything looks good! 🍰

**Comment by Nima-ShSh** [comment]
Tested and it looks great!

**Pull request merged**
