### PR TITLE
Ticket 10: Create Category | Complete

### PR DESCRIPTION
**Pull request by ded-possum**
# Description

This code addresses Ticket #10: Create a Category. Once implemented, users can navigate to Categories and click Create New to enter the name of a new category.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Testing Instructions
- In terminal, run "git fetch --all" to view all branches
- In terminal, run "git checkout spcategories" to enter the branch related to this PR
- run TabloidMVC.sln application from branch spcategories
- in application, navigate to Login
- use "admin@example.com" to log in to the application
- upon successful login, navigate to Categories via the link in the navbar
- in Categories, click the Create New link in the top right
- User should be presented with a form field for Name
- Name a new category and check to ensure the new category populates in the Categories list
- To ensure new category(ies) has/have been added to the list of all categories that is currently being displayed,
- Select TabloidMVC Database, right-click and select New Query 
- Type the following into your Query: SELECT * FROM Category;
- Ctrl-Shift-E to run the Query
- A table will be populated with all existing Categories in the Database
- Locate the newly added category in the SQL query to validate the display results on the browser window

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Nima-ShSh** [comment]
Looks good! ⭐

**Comment by MelQuan95** [comment]
worked for me! looks good.

**Comment by sarahebrooks12** [comment]
Need either a list of all categories that should be shown in application or a SQL query that will show that so tester can compare and contrast

**Comment by sarahebrooks12** [comment]
How do I log in to application? What data should I be using?

**Comment by sarahebrooks12** [comment]
Please see other teams closed pull requests as examples or refer to Swathi's

**Comment by sarahebrooks12** [comment]
👼

**Pull request merged**
